# create a list of tags for testing
tag_test <- section_tags(
  heading = "hello",
  body = "body"
)

test_that("section_tags outputs are as expected", {
  expect_equal(paste(tag_test[[1]]), "<h2>hello</h2>")

  expect_equal(paste(tag_test[[2]]), "<p>body</p>")
})

# testing errors
test_that("no error is generated by section_tags with normal inputs", {
  expect_no_error(section_tags("a", "b"))

  expect_no_error(section_tags("a", "b", h_level = "h4"))

  expect_no_error(section_tags("a", "b", h_level = "h3"))

  expect_no_error(section_tags(
    heading = shiny::tagList("heading1", "heading2"),
    body = shiny::tagList("body1", "body2")
  ))
})

test_that("errors are being generated for no/wrong inputs", {
  # error for not providing a body argument
  expect_error(
    section_tags(heading = "a")
  )

  # error for not providing an unavailable h_level argument
  expect_error(
    section_tags(
      heading = "a",
      body = "b",
      h_level = "h1"
    )
  )

  # error for wrapping in c() instead of shiny::tagList()
  expect_error(section_tags(heading = "a", body = c(
    "b",
    dfeshiny::external_link(
      href = paste0("mailto:", "team@education.gov.uk"),
      link_text = "team@education.gov.uk",
      add_warning = FALSE
    )
  )))

  expect_error(section_tags(heading = c(
    "a",
    dfeshiny::external_link(
      href = paste0("mailto:", "team@education.gov.uk"),
      link_text = "team@education.gov.uk",
      add_warning = FALSE
    )
  ), body = "c"))
})

# testing outputs

output_1 <- section_tags(body = "body text")

output_2 <- section_tags(
  heading = "a",
  body = "b"
)

output_3 <- section_tags(
  heading = "a",
  body = "b",
  h_level = "h4"
)

output_4 <- section_tags(
  heading = shiny::tagList("heading1", "heading2"),
  body = shiny::tagList("body1", "body2"),
  h_level = "h4"
)

test_that("test that the outputs are as expected", {
  expect_equal(paste(output_1[[1]]), "<p>body text</p>")

  expect_equal(paste(output_2[[1]]), "<h2>a</h2>")
  expect_equal(paste(output_2[[2]]), "<p>b</p>")

  expect_equal(paste(output_3[[1]]), "<h4>a</h4>")
  expect_equal(paste(output_3[[2]]), "<p>b</p>")

  expect_equal(paste(output_4[[1]]), "<h4>\n  heading1\n  heading2\n</h4>")
  expect_equal(paste(output_4[[2]]), "<p>\n  body1\n  body2\n</p>")
})
