# create a list of tags for testing
tag_test <- html_paragraph_tags(
  heading = "hello",
  body = "body"
)

test_that("html_paragraph_tags outputs are as expected", {
  expect_equal(paste(tag_test[[1]]), "<h2>hello</h2>")

  expect_equal(paste(tag_test[[2]]), "<p>body</p>")
})

# testing errors
test_that("no error is generated by html_paragraph_tags with normal inputs", {
  expect_no_error(html_paragraph_tags("a", "b"))
})

test_that("errors are being generated for no/wrong inputs", {
  expect_error(
    html_paragraph(heading = "a"),
    "Please provide a character vector for the " / body / " argument"
  )

  expect_error(
    html_paragraph(body = "a"),
    "Please provide a character vector for the " / heading / " argument"
  )

  # expect_error(html_paragraph(heading=1, body=2)
  #              , "Please provide a character vector for the "/body/" argument")
})
