# create a list of tags for testing
tag_test <- section_tags(
  heading = "hello",
  body = "body"
)

test_that("section_tags outputs are as expected", {
  expect_equal(paste(tag_test[[1]]), "<h2>hello</h2>")

  expect_equal(paste(tag_test[[2]]), "<p>body</p>")
})

# testing errors
test_that("no error is generated by section_tags with normal inputs", {
  expect_no_error(section_tags("a", "b"))
})

test_that("errors are being generated for no/wrong inputs", {
  expect_error(
    section_tags(heading = "a")
  )


  expect_error(section_tags(heading = "a", body = c(
    "b",
    dfeshiny::external_link(
      href = paste0("mailto:", "team@education.gov.uk"),
      link_text = "team@education.gov.uk",
      add_warning = FALSE
    )
  )))

  expect_error(section_tags(heading = c(
    "a",
    dfeshiny::external_link(
      href = paste0("mailto:", "team@education.gov.uk"),
      link_text = "team@education.gov.uk",
      add_warning = FALSE
    )
  ), body = "c"))
})
