name: Deploy Dashboard
on:
  push:
    branches:
      - test_deployment
jobs:
  deploy:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/deploy-dashboard-template.yaml
    with:
      parameter_file: deploy-parameters.yaml
