name: Deploy Dashboard
on:
  push:
    branches:
      - test_deployment
jobs:
  deploy:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/dashboard-deploy-template.yaml@test_deployment
    with:
      parameter_file: deploy-parameters.yaml
