name: Deploy Dashboard
on:
  push:
    branches:
      - test_deployment
jobs:
  deploy:
    uses: dfeshiny/.github/workflows/deploy-dashboard-template.yaml@develop
    with:
      parameter_file: deploy-parameters.yaml
