name: lintr scan

on:
  workflow_call:
    inputs:
      is_package:
        description: "Is this part of a package"
        default: 'false'
        required: false
        type: string
    secrets:
      SHINYAPPS_SECRET:
        required: true
      SHINYAPPS_TOKEN:
        required: true

jobs:
  lintr:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/dfe-analytical-services/dfe-r-base:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        if: ${{ inputs.is_package == 'true' }}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            lintr
            cyclocomp

      - name: Run lintr
        run: lintr::sarif_output(lintr::lint_dir("."), "lintr-results.sarif")
        shell: Rscript {0}
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: lintr-results.sarif
          wait-for-processing: true
