name: tidy code

on:
  workflow_call:
    inputs:
      is_package:
        description: "Is this part of a package (true / false)"
        default: 'false'
        required: false
        type: string
      method:
        description: "Which method to use (styler / air)"
        default: 'styler'
        required: false
        type: string

jobs:
  lintr:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/dfe-analytical-services/dfe-r-base:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        if: ${{ inputs.is_package == 'true' }}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            styler

      - name: renv restore packages
        if: ${{ inputs.is_package == 'false' }}
        run: |
          renv::restore()
          renv::install("styler")
        shell: Rscript {0}

      - name: Tidy code
        shell: Rscript {0}
        run: |
            codeChecks <- dfeshiny::tidy_code()

            if(any(is.na(codeChecks))) {
              stop("There is a breaking error in the code.")
            } else {
              if(TRUE %in% codeChecks) {
                stop("The code is not styled correctly. Open the project in RStudio and use tidy_code() to restyle the code.")
              } else {
                message("----------------------------------------")
                message("The code is beautiful, go you!")
                message("----------------------------------------")
              }
            }
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-tests
          path: tests
