name: Trello PR card
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  create-card:
    runs-on: ubuntu-latest
    steps:
      - name: create a card
        uses: nentgroup/pr-trello-card@v1
        with:
          api-key: '${{ secrets.TRELLO_API_KEY }}'
          api-token: '${{ secrets.TRELLO_API_TOKEN }}'
          list-id: '63ce5064a4859b0387f46b9b'
          title-format: 'dfeshiny PR: ${title}'
          label-ids: '63ce4ffcbfa825468a8e2a69'
